spring.application.name=kadai

# ----- H2 Database接続 -----
#spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa	
#spring.datasource.password=
#spring.sql.init.encoding=UTF-8 	
#spring.datasource.initialize=true
#spring.jpa.hibernate.ddl-auto=none
#spring.sql.init.schema-locations=classpath:sql/schema.sql 	
#spring.sql.init.data-locations=classpath:sql/data.sql
#spring.datasource.generate-unique-name=false 	


# ----- MariaDB接続 ----- 中安さんのやつ
#spring.datasource.url=jdbc:mariadb://13.159.38.108:3306/kensyu26db
#spring.datasource.username=kadai26
#spring.datasource.password=kadai26

#spring.datasource.hikari.maximum-pool-size=5
#spring.datasource.hikari.minimum-idle=1
#spring.jpa.open-in-view=false



# ----- MariaDB接続 ----- 
spring.datasource.url=jdbc:mariadb://10.0.20.182:3306/team8_db
spring.datasource.username=app_user
spring.datasource.password=Bold-08

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.jpa.open-in-view=false
